### ISSUE TITLE
<string>.decode() doesn't take keyword arg on python2.6

### ISSUE THREAD

**Issue by blalor** [shawnsi/docker-rpmbuild#23]
`rpmbuild.build:main` fails on python 2.6.6 because `line.decode` doesn't accept the `encoding` keyword arg.  It does work on python2.7; not sure how to reconcile that with python3.

https://github.com/shawnsi/docker-rpmbuild/blob/master/rpmbuild/build.py#L75

**Comment by shawnsi** [comment]
I'm not sure on best approach here.  Maybe a try/except clause to handle python 2.6?

Will accept a pull request that resolves the issue but I don't need this fixed myself.
